language: node_js
node_js:
  - 8
script:
  - npm run build
deploy:
  provider: surge
  project: ./dist
  domain: epu-notebook.surge.sh
  skip_cleanup: true
cache:
  directories:
    - './node_modules'
